// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ChatConfig is the predicate function for chatconfig builders.
type ChatConfig func(*sql.Selector)
