definitions:
  chatSerializer.ChatBodyRequest:
    properties:
      device_code:
        type: string
      image:
        description: Image      *multipart.FileHeader `form:"image" binding:"omitempty"`
        type: string
      message:
        type: string
    required:
    - device_code
    - message
    type: object
  chatSerializer.ChatReply:
    properties:
      func_name:
        type: string
      reply_msg:
        type: string
    type: object
  chatSerializer.GlassesConfigRequest:
    properties:
      device_code:
        type: string
      discord_user_id:
        type: string
      forward_mode:
        enum:
        - all
        - media
        type: string
    required:
    - device_code
    - forward_mode
    type: object
  chatSerializer.VoiceChatBodyRequest:
    properties:
      deviceCode:
        type: string
    required:
    - deviceCode
    type: object
  ent.ChatConfig:
    properties:
      create_time:
        description: CreateTime holds the value of the "create_time" field.
        type: string
      device_code:
        description: DeviceCode holds the value of the "device_code" field.
        type: string
      discord_user_id:
        description: DiscordUserID holds the value of the "discord_user_id" field.
        type: string
      forward_mode:
        description: ForwardMode holds the value of the "forward_mode" field.
        type: string
      id:
        description: ID of the ent.
        type: integer
      update_time:
        description: UpdateTime holds the value of the "update_time" field.
        type: string
    type: object
info:
  contact: {}
paths:
  /chat:
    post:
      consumes:
      - application/json
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/chatSerializer.VoiceChatBodyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/chatSerializer.ChatReply'
      security:
      - ApiKeyAuth: []
      summary: AI 语音聊天接口
      tags:
      - AI
  /chat/earphone-config:
    post:
      consumes:
      - application/json
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/chatSerializer.GlassesConfigRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ent.ChatConfig'
      security:
      - ApiKeyAuth: []
      summary: AI 耳机配置接口
      tags:
      - AI
swagger: "2.0"
