// Code generated by ent, DO NOT EDIT.

package ent

import (
	"angrymiao-ai/app/ent/chatconfig"
	"angrymiao-ai/app/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chatconfigMixin := schema.ChatConfig{}.Mixin()
	chatconfigMixinFields0 := chatconfigMixin[0].Fields()
	_ = chatconfigMixinFields0
	chatconfigFields := schema.ChatConfig{}.Fields()
	_ = chatconfigFields
	// chatconfigDescCreateTime is the schema descriptor for create_time field.
	chatconfigDescCreateTime := chatconfigMixinFields0[0].Descriptor()
	// chatconfig.DefaultCreateTime holds the default value on creation for the create_time field.
	chatconfig.DefaultCreateTime = chatconfigDescCreateTime.Default.(func() time.Time)
	// chatconfigDescUpdateTime is the schema descriptor for update_time field.
	chatconfigDescUpdateTime := chatconfigMixinFields0[1].Descriptor()
	// chatconfig.DefaultUpdateTime holds the default value on creation for the update_time field.
	chatconfig.DefaultUpdateTime = chatconfigDescUpdateTime.Default.(func() time.Time)
	// chatconfig.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	chatconfig.UpdateDefaultUpdateTime = chatconfigDescUpdateTime.UpdateDefault.(func() time.Time)
	// chatconfigDescDeviceCode is the schema descriptor for device_code field.
	chatconfigDescDeviceCode := chatconfigFields[0].Descriptor()
	// chatconfig.DeviceCodeValidator is a validator for the "device_code" field. It is called by the builders before save.
	chatconfig.DeviceCodeValidator = chatconfigDescDeviceCode.Validators[0].(func(string) error)
}
