// Code generated by ent, DO NOT EDIT.

package chatconfig

import (
	"fmt"
	"time"
)

const (
	// Label holds the string label denoting the chatconfig type in the database.
	Label = "chat_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldDeviceCode holds the string denoting the device_code field in the database.
	FieldDeviceCode = "device_code"
	// FieldDiscordUserID holds the string denoting the discord_user_id field in the database.
	FieldDiscordUserID = "discord_user_id"
	// FieldForwardMode holds the string denoting the forward_mode field in the database.
	FieldForwardMode = "forward_mode"
	// Table holds the table name of the chatconfig in the database.
	Table = "chat_config"
)

// Columns holds all SQL columns for chatconfig fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDeviceCode,
	FieldDiscordUserID,
	FieldForwardMode,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DeviceCodeValidator is a validator for the "device_code" field. It is called by the builders before save.
	DeviceCodeValidator func(string) error
)

// ForwardMode defines the type for the "forward_mode" enum field.
type ForwardMode string

// ForwardModeAll is the default value of the ForwardMode enum.
const DefaultForwardMode = ForwardModeAll

// ForwardMode values.
const (
	ForwardModeAll   ForwardMode = "all"
	ForwardModeMedia ForwardMode = "media"
)

func (fm ForwardMode) String() string {
	return string(fm)
}

// ForwardModeValidator is a validator for the "forward_mode" field enum values. It is called by the builders before save.
func ForwardModeValidator(fm ForwardMode) error {
	switch fm {
	case ForwardModeAll, ForwardModeMedia:
		return nil
	default:
		return fmt.Errorf("chatconfig: invalid enum value for forward_mode field: %q", fm)
	}
}
